In [1]:
import numpy as np

In [3]:
"""
자기관찰(instropection)
 - 객체가 함수이거나 인스턴스 메서드라면 정의되어있는 문서(docstring) 을 출력해준다.
"""
# instropection example
print?

# 물음표 2개를 붙일경우 사용 가능한 소스코드를 보여준다.

Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.
Optional keyword arguments:
file:  a file-like object (stream); defaults to the current sys.stdout.
sep:   string inserted between values, default a space.
end:   string appended after the last value, default a newline.
flush: whether to forcibly flush the stream.
Type:      builtin_function_or_method


In [9]:
import numpy as np

# 네임스페이스를 검색하는데 사용할 수 있다.
np.*load*?


np.__loader__
np.load
np.loads
np.loadtxt

In [13]:
"""
%run 명령어는 IPython 세션안에서 파이썬 프로그램 파일을 불러와서 실행할 수 있다.
"""

"""
 -- ipython_script_test.py 소스코드
def f(x,y,z):
    return (x+y)/z

a=5
b=6
c=7.5

result = f(a,b,c)
print(result)
"""

%run ipython_script_test.py

external = f(5,6,7)
print(external)

print(a)

1.4666666666666666
1.5714285714285714
5


In [19]:
import numpy as np

"""
numpy와 Python 기본 함수 속도 측정
"""

# NumPy 에서 제공되는 배열
my_arr = np.arange(1000000)

# Python 리스트
my_list = list(range(1000000))

# 각 리스트 원소에 2를 곱한다.
%time for _ in range(10): my_arr2 = my_arr*2

# 각 리스트 원소에 2를 곱한다.
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 32 ms
Wall time: 907 ms


In [23]:
"""
 다차원 배열 객체
"""

import numpy as np

data = np.random.randn(2,3) # 2 Row, 3 Column 배열 객체 생성
print(data)
print()
print("data 객체에 10을 곱할경우")
print(data * 10) # 각 원소에 10을 곱하여 반환한다.
print()
print("data 객체끼리 더할경우")
print(data + data)


[[-2.11583949 -0.84194109  1.4487259 ]
 [ 1.51466148  1.2599737   1.23019899]]

data 객체에 10을 곱할경우
[[-21.15839494  -8.41941086  14.48725904]
 [ 15.14661484  12.59973703  12.30198986]]

data 객체끼리 더할경우
[[-4.23167899 -1.68388217  2.89745181]
 [ 3.02932297  2.51994741  2.46039797]]


In [27]:
"""
모든 배열은 각 차원의 크기를 알려주는 
shape 라는 튜플과 배열에 저장된 자료형을 알려주는 
dtype 객체를 가진다.
"""
print('---'*20)
print(data.shape) # 튜플형태로 차원의 크기를 반환한다.
print('---'*20)
print(data.dtype)

------------------------------------------------------------
(2, 3)
------------------------------------------------------------
float64


In [37]:
"""
ndarray의 모든 원소는 같은 자료형이어야 한다.
"""

# ndarray 생성
data1 = [6,7.5,8,0,1]
arr1  = np.array(data1)

print("리스트 to ndarray \n",arr1)
print()

data2 = [[1,2,3,4],[5,6,7,8]]
arr2  = np.array(data2)
print("다차원 배열 to ndarray \n",arr2)

print("dimension : ",arr2.ndim)  # 차수, 차원의 수 dimension
print("shape     : ",arr2.shape) # 행렬 

리스트 to ndarray 
 [6.  7.5 8.  0.  1. ]

다차원 배열 to ndarray 
 [[1 2 3 4]
 [5 6 7 8]]
dimension :  2
shape     :  (2, 4)


In [45]:
"""
ndarray 초기화
"""

_zeros = np.zeros(10) # 0으로 초기화된 배열
print(_zeros) 
print("---" * 20)
# Row 을 10개 가지며 Column 을 2개 가지는 배열
_zeros_2 = np.zeros((10, 2))  
print(_zeros_2)

print("---"*20)

_np_arange = np.arange(15)
print(_np_arange)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------------------------------------------------------
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
------------------------------------------------------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [54]:
"""
np.array 의 중요 특징
for 문을 사용하지 않고 데이터를 일괄 처리할 수 있다.
-> 벡터화 라고 한다.

같은 크기의 배열 간의 산술연산은 배열의 각 원소 단위로 적용된다.
"""

arr = np.array([[1., 2., 3.],[4.,5.,6.]])

print(arr)

print('---'* 20)
print(arr * arr)

print('---'* 20)
print(arr + arr)

print('---'* 20)
print(arr - arr)

"""
스칼라 인자가 포함된 산술 연산의 경우 배열내의 모든 원소에 스칼라인자가 적용된다.
"""
print('---'* 20)
print(1/arr)

"""
같은 크기를 가지는 배열간의 배교연산은 불리언 배열을 반환한다.
"""

arr2 = np.array([[0.,4.,1.], [7.,2.,12.]])
print('---'* 20)
print( arr > arr2)


[[1. 2. 3.]
 [4. 5. 6.]]
------------------------------------------------------------
[[ 1.  4.  9.]
 [16. 25. 36.]]
------------------------------------------------------------
[[ 2.  4.  6.]
 [ 8. 10. 12.]]
------------------------------------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
------------------------------------------------------------
[[ True False  True]
 [False  True False]]
